### ISSUE TITLE
IndexError: list index out of range - Error coming alot in log

### ISSUE THREAD

**Issue by DKAutomater** [JonasPed/homeassistant-eloverblik#6]
Hi

I got these error on each sensor.eloverblik_energy

2020-03-31 15:06:57 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.eloverblik_energy_23_24 fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 279, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 476, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/eloverblik/sensor.py", line 81, in update
    self._state = self._data.get_usage_hour(self._hour)
  File "/config/custom_components/eloverblik/__init__.py", line 77, in get_usage_hour
    return round(self._data.get_metering_data(hour), 3)
  File "/usr/local/lib/python3.7/site-packages/pyeloverblik/models.py", line 53, in get_metering_data
    return self._metering_data[hour-1]
IndexError: list index out of range

**Comment by JonasPed** [comment]
This is due to daylight saving. It should only happen with data for that single day each year. With a bit of luck I will get it fixed before next year :-)

**Comment by JonasPed** [comment]
Closed by #34e309db25410a0e28252d0dfde516fc067f0be3.
