### ISSUE TITLE
Nordpool integration issue

### ISSUE THREAD

**Issue by stokbaek** [JonasPed/homeassistant-eloverblik#66]
I have tried to integrate nordpool but I am getting the following stacktrace in the log. It seems to work if I am using the template tester in the home-assistant UI

```
2022-12-11 14:44:09.314 ERROR (MainThread) [homeassistant.helpers.event] Error while processing template: Template("{{ (1.25 * float(states('sensor.eloverblik_tariff_sum'))) + float(states('sensor.nordpool_kwh_dk2_dkk_2_10_025')) }}")
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1700, in forgiving_float
    return float(value)
ValueError: could not convert string to float: 'unknown'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 423, in async_render
    render_result = _render_with_context(self.template, compiled, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1942, in _render_with_context
    return template.render(**kwargs)
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
  File "/usr/local/lib/python3.10/site-packages/jinja2/sandbox.py", line 393, in call
    return __context.call(__obj, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1703, in forgiving_float
    raise_no_default("float", value)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1411, in raise_no_default
    raise ValueError(
ValueError: Template error: float got invalid input 'unknown' when rendering template '{{ (1.25 * float(states('sensor.eloverblik_tariff_sum'))) + float(states('sensor.nordpool_kwh_dk2_dkk_2_10_025')) }}' but no default was specified
```

**Comment by JonasPed** [comment]
Looks like your sensor don't display any valid data?

**Comment by stokbaek** [comment]
as far as I can see do I have data. But as soon as I tried to use `sensor.electricity_cost` in a graph I am getting that stacktrace

![image](https://user-images.githubusercontent.com/5165133/207438825-6c1e3c3e-449e-4863-90b4-e46a0ec2dbae.png)

**Comment by JonasPed** [comment]
Can you please paste how the two below sensors look under developer tools -> states?

sensor.eloverblik_tariff_sum
sensor.nordpool_kwh_dk2_dkk_2_10_025

**Comment by stokbaek** [comment]
![image](https://user-images.githubusercontent.com/5165133/209482272-3d7627e8-4bc4-481d-88ac-81e8bf3da9c2.png)
![image](https://user-images.githubusercontent.com/5165133/209482295-b1da969e-d796-455f-a97d-a3b6a8289033.png)

**Comment by JonasPed** [comment]
The sensor data looks OK to me. 

Is it only when using sensor.electricity_cost in a chart/graph you have the issue? How does the sensor sensor.electricity_cost look under developer tools?

**Comment by stokbaek** [comment]
seems like it cannot collect data?
![image](https://user-images.githubusercontent.com/5165133/209483552-436fb337-fdd6-43c4-8a0c-37ef8eeeee7c.png)

**Comment by JonasPed** [comment]
I am quite sure that you have an issue with the sensor template you have pasted in your configuration file. As per your screenshots the source sensor is showing correct values, so I don't think it is an issue with the integraiton.

**Comment by stokbaek** [comment]
managed to get it to work but seems like nordpool broke now. All my tomorrow values are null now, but this is not related to this project
