### ISSUE TITLE
Unsupported operand type(s) for -: 'datetime.datetime' and 'float'

### ISSUE THREAD

**Issue by DurgNomis-drol** [JonasPed/homeassistant-eloverblik#78]
Jeg får denne fejl meddelelse: 
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 541, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 739, in async_device_update
    raise exc
  File "/config/custom_components/eloverblik/sensor.py", line 234, in async_update
    if last_stat is not None and pytz.utc.localize(datetime.now()) - last_stat["start"] < timedelta(days=1):
TypeError: unsupported operand type(s) for -: 'datetime.datetime' and 'float'
```

Men integration virker fint 😃

**Comment by edtwodth** [comment]
Har samme problem
