### ISSUE TITLE
Får ikke data (har vedhæftet log)

### ISSUE THREAD

**Issue by fontexD** [JonasPed/homeassistant-eloverblik#88]
alt data står som ukendt pt har prøvet genindlæse

Logger: homeassistant.config_entries
Source: custom_components/eloverblik/sensor.py:227
Integration: Eloverblik
First occurred: 08.59.22 (1 occurrences)
Last logged: 08.59.22

Error unloading entry Eloverblik 571313114300004272 for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 543, in async_unload
    result = await component.async_unload_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 137, in async_unload_entry
    return await component.async_unload_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 196, in async_unload_entry
    await platform.async_reset()
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 745, in async_reset
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 867, in async_remove
    await self.async_will_remove_from_hass()
  File "/config/custom_components/eloverblik/sensor.py", line 227, in async_will_remove_from_hass
    await get_instance(self.hass).async_clear_statistics([self.entity_id])
TypeError: object NoneType can't be used in 'await' expression****

**Comment by fontexD** [comment]
> alt data står som ukendt pt har prøvet genindlæse
> 
> Logger: homeassistant.config_entries Source: custom_components/eloverblik/sensor.py:227 Integration: Eloverblik First occurred: 08.59.22 (1 occurrences) Last logged: 08.59.22
> 
> Error unloading entry Eloverblik 571313114300004272 for sensor Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/config_entries.py", line 543, in async_unload result = await component.async_unload_entry(hass, self) File "/usr/src/homeassistant/homeassistant/components/sensor/**init**.py", line 137, in async_unload_entry return await component.async_unload_entry(entry) File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 196, in async_unload_entry await platform.async_reset() File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 745, in async_reset await asyncio.gather(_tasks) File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 867, in async_remove await self.async_will_remove_from_hass() File "/config/custom_components/eloverblik/sensor.py", line 227, in async_will_remove_from_hass await get_instance(self.hass).async_clear_statistics([self.entity_id]) TypeError: object NoneType can't be used in 'await' expression_***

jeg prøvede lige lave et get request mod deres api og det ser ud til det eloverblik der har problemer pt
